### Data Encoding

1. Nominal/ One Hot Encoding (OHE)
2. Label and ordinal Encoding
3. Target Encoding

### Nominal / OHE (used in catagorical data)

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.DataFrame({'color':['red','blue','green','red','blue']})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [5]:
encoder = OneHotEncoder()

In [6]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [9]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Label Encoding (Encode the values based on frequency wise in alphabetical order)

In [10]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lbl_encoder = LabelEncoder()

In [13]:
lbl_encoder.fit_transform(df['color'])

array([2, 0, 1, 2, 0])

In [17]:
lbl_encoder.fit_transform(df['color'] == 'red')

array([1, 0, 0, 1, 0])

### Ordinal Encoding (Categorical Data encode the data Based on order wise)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [23]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [24]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [25]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])